# Generated by Django 4.1.2 on 2023-02-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odgovori',
            name='tocanOdg',
        ),
        migrations.AddField(
            model_name='odgovori',
            name='tocan_odg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kviz',
            name='tezina',
            field=models.IntegerField(default=0),
        ),
    ]
