# Generated by Django 4.1.2 on 2023-02-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_osoba_prijavljenazakviz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=20)),
                ('prezime', models.CharField(max_length=20)),
                ('godine', models.IntegerField()),
            ],
        ),
    ]
