# Generated by Django 4.1.4 on 2023-02-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_kandidat_ime_alter_kandidat_prezime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odgovori',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='odgovori',
            name='tocan_odg',
            field=models.BooleanField(),
        ),
    ]
